import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BsMoonStarsFill } from "react-icons/bs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Anand&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="min-h-screen bg-gray-300">
          <nav className="py-5 mb-10 flex justify-between">
            <h1>Anand Menon</h1>
            <ul className="px-2  flex items-center">
              <li className="ml-4">About</li>
              <li className="ml-4">Projects</li>
              <li className="ml-4 ">
                <a href="#">Resume</a>
              </li>
              
              <li className="ml-4 mr-4">
                <BsMoonStarsFill />
              </li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
  );
}
