import Head from "next/head";

import { BsMoonStarsFill } from "react-icons/bs";
import { AiFillBehanceCircle, AiFillGithub, AiFillLinkedin, AiFillMail } from "react-icons/ai";
import { FaDiscord } from "react-icons/fa";
import Image from "next/image";
import yoo from "../public/yoo.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Anand&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon_1.png" />
      </Head>

      <main>
        <section className="min-h-screen ">

          {/* <div className=" flex  justify-between items-center">
            
          </div> */}
          <nav className="py-5 mb-10 flex justify-between ">
          <h1 className=" text-lg ml-20 font-akira ">AM</h1>
            <ul className="  flex  mr-5 items-center ">
            
           
           
              <li className="ml-4   text-md ">Work.</li>
              <li className=" ml-4 text-md ">
                <a href="#">Resume</a>
              </li>
              
              <li className="ml-4 mr-4">
                <BsMoonStarsFill className=" " />
              </li>
            </ul>
          </nav>

            <div className=" pt-10 py-10 px-20 text-center ">
                <h2 className="font-bold text-4xl font-mono text-teal-600 ">Anand Menon</h2>
                <h3 className="font-semibold text-xl  "> Learning Enthusiast </h3>
                <p className= " font-medium text-lg text-slate-500"> *NOT* a Frontend Developer. </p>
                <p className= " font-medium text-md text-slate-500"> Connect me down and let&apos;s tinker around. </p>
            </div>

            <div className=" flex  justify-center ml-10 mr-10  gap-4 text-3xl text-gray-700 ">
              <a href="https://linkedin.com/in/anandsm08"><AiFillLinkedin /></a>
              <a href="https://github.com/anandsm08"><AiFillGithub /></a>
              <a href="mailto:codinand@gmail.com"><AiFillMail /></a>
              <a href="https://discordapp.com/users/264769172104413196"><FaDiscord /></a>
            </div>

            <div className=" relative mx-auto  mt-20 py-20 h-80 w-80">
              <Image src={yoo} alt=""  className="bg-gradient-to-b from-slate-400  to-white rounded-full" layout="fill" objectFit="cover"/>
            </div>
        </section>

          <section>
            <div className="mx-10 ">
              <h2 className="text-3xl font-mono">About</h2>
              <p className="font-medium">Hey there! Anand this side, I love learning </p>
            </div>

          </section>


      </main>
    </div>
  );
}
